#App
spring:
  application:
    name: edge-server

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

#Logs
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

#Routes
spring.cloud.gateway.routes:
  - id: service1
    uri: http:/localhost:8081
    predicates:
      - Path=/service1/**
  - id: service2
    uri: http:/localhost:8082
    predicates:
      - Path=/service2/**
  - id: eureka-ui
    uri: http://localhost:8761
    predicates:
      - Path=/eurekawebui
  - id: eureka-css-js
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/**